---
- name: Setup local machine
  hosts: localhost
  connection: local

  roles:
    - { role: base, tags: base }
    - { role: shell, tags: shell }
    - { role: desktop, tags: desktop }
    - { role: containers, tags: containers }
    - { role: dev, tags: dev }
