---
- name: Provision Local Development Workstation
  hosts: localhost
  become: true
  roles:
    - { role: base, tags: base }
    - { role: shell, tags: shell }
    - { role: desktop, tags: desktop }
    - { role: containers, tags: containers }
    - { role: development, tags: development }
