---

- name: Install 1Password
  ansible.builtin.import_tasks: 1password/install.yml

- name: Configure 1Password shortcuts
  ansible.builtin.import_tasks: 1password/shortcuts.yml

- name: Configure Firefox integration
  ansible.builtin.import_tasks: 1password/firefox.yml
