---
- name: Enable Flathub for Flatpak apps
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Desktop Flatpak applications
  community.general.flatpak:
    name:
      - org.ferdium.Ferdium
      - com.mattjakeman.ExtensionManager
    state: present
