---
- name: Install Desktop applications
  ansible.builtin.dnf:
    name:
      - gnome-tweaks
    state: present

- name: Enable Flathub for Flatpak apps
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Desktop Flatpak applications
  community.general.flatpak:
    name:
      - org.ferdium.Ferdium # Ferdium
      - com.google.Chrome # Google Chrome
      - com.spotify.Client # Spotify
      - com.mattjakeman.ExtensionManager # Extension Manager
      - com.github.IsmaelMartinez.teams_for_linux # Teams for Linux
      - com.github.tchx84.Flatseal # Flatseal
      - io.missioncenter.MissionCenter # Mission Center
      - org.localsend.localsend_app # LocalSend
      - it.miamotors.GearLever # Gearlever
      - com.brave.Browser # Brave
      - io.podman_desktop.PodmanDesktop # Podman Desktop
      - com.github.marhkb.Pods # Pods
      - com.valvesoftware.Steam # Steam
      - com.mojang.Minecraft # Minecraft
      - com.protonvpn.www # Proton VPN
      - io.github.kolunmi.Bazaar # Bazaar
      - io.github.mfat.sshpilot # SSH Pilot
      - io.github.mrvladus.List # Errands
      - io.github.pwr_solaar.solaar # Solaar
      - io.gitlab.metadatacleaner.metadatacleaner # Metadata Cleaner
      - md.obsidian.Obsidian # Obsidian
      - me.timschneeberger.GalaxyBudsClient # Galaxy Buds Client
      - org.gimp.GIMP # GIMP
      - org.mozilla.firefox # Firefox
      - org.qbittorrent.qBittorrent # qBittorrent
      - org.videolan.VLC # VLC
      - org.zaproxy.ZAP # ZAP
      - org.zotero.Zotero # Zotero
      - dev.qwery.AddWater # Add Water
      - com.getpostman.Postman # Postman
    state: present
  become: true
