---

- name: Configure desktop packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure Flatpak applications
  ansible.builtin.import_tasks: flatpak.yml

- name: Configure GNOME extensions
  ansible.builtin.import_tasks: gnome.yml

- name: Configure 1Password
  ansible.builtin.import_tasks: 1password.yml
