---

- name: Register the Microsoft repository
  become: true
  ansible.builtin.dnf:
    name: "https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm"
    state: present
    disable_gpg_check: true

- name: Keep .NET packages on Fedora's repos
  become: true
  community.general.ini_file:
    path: /etc/yum.repos.d/microsoft-prod.repo
    section: packages-microsoft-com-prod
    option: exclude
    value: dotnet* aspnetcore* netstandard*
    no_extra_spaces: true
    mode: '0644'

- name: Install PowerShell
  become: true
  ansible.builtin.dnf:
    name: powershell
    state: present
    update_cache: true
