---
- name: Enable Flathub for Flatpak apps
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak applications
  community.general.flatpak:
    name:
      - com.getpostman.Postman
      - org.ferdium.Ferdium
    state: present
