---
- name: Update all system packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  # noqa: package-latest

- name: Install core system packages
  ansible.builtin.dnf:
    name:
      - gnome-tweaks
    state: present
