personal_installed_flatpaks:
- com.brave.Browser
- com.getpostman.Postman
- com.github.IsmaelMartinez.teams_for_linux
- com.github.marhkb.Pods
- com.github.tchx84.Flatseal
- com.mattjakeman.ExtensionManager
- com.protonvpn.www
- com.spotify.Client
- com.valvesoftware.Steam
- dev.qwery.AddWater
- io.github.kolunmi.Bazaar
- io.github.mfat.sshpilot
- io.github.mrvladus.List
- io.github.pwr_solaar.solaar
- io.gitlab.metadatacleaner.metadatacleaner
- io.missioncenter.MissionCenter
- io.podman_desktop.PodmanDesktop
- it.mijorus.gearlever
- md.obsidian.Obsidian
- me.timschneeberger.GalaxyBudsClient
- org.ferdium.Ferdium
- org.gimp.GIMP
- org.localsend.localsend_app
- org.mozilla.firefox
- org.qbittorrent.qBittorrent
- org.videolan.VLC
- org.zotero.Zotero
- xyz.ketok.Speedtest
