---

desktop_packages:
  - gnome-tweaks
  - flatpak
  - ptyxis
  - python3-psutil

desktop_flatpak_apps:
  - org.ferdium.Ferdium # Ferdium
  - com.google.Chrome # Google Chrome
  - com.spotify.Client # Spotify
  - com.mattjakeman.ExtensionManager # Extension Manager
  - com.github.tchx84.Flatseal # Flatseal
  - io.missioncenter.MissionCenter # Mission Center
  - org.localsend.localsend_app # LocalSend
  - it.mijorus.gearlever # Gearlever
  - com.brave.Browser # Brave
  - io.podman_desktop.PodmanDesktop # Podman Desktop
  - com.github.marhkb.Pods # Pods
  - com.valvesoftware.Steam # Steam
  - com.mojang.Minecraft # Minecraft
  - com.protonvpn.www # Proton VPN
  - io.github.kolunmi.Bazaar # Bazaar
  - io.github.mfat.sshpilot # SSH Pilot
  - io.github.mrvladus.List # Errands
  - io.github.pwr_solaar.solaar # Solaar
  - io.gitlab.metadatacleaner.metadatacleaner # Metadata Cleaner
  - md.obsidian.Obsidian # Obsidian
  - me.timschneeberger.GalaxyBudsClient # Galaxy Buds Client
  - org.gimp.GIMP # GIMP
  - org.mozilla.firefox # Firefox
  - org.qbittorrent.qBittorrent # qBittorrent
  - org.videolan.VLC # VLC
  - org.zaproxy.ZAP # ZAP
  - org.zotero.Zotero # Zotero
  - com.getpostman.Postman # Postman
  - xyz.ketok.Speedtest # Present on the source laptop

desktop_work_flatpak_apps:
  - com.github.IsmaelMartinez.teams_for_linux # Teams for Linux

desktop_gnome_extensions:
  - caffeine@patapon.info
  - dash-to-dock@micxgx.gmail.com
  - appindicatorsupport@rgcjonas.gmail.com
  - apps-menu@gnome-shell-extensions.gcampax.github.com
  - launch-new-instance@gnome-shell-extensions.gcampax.github.com
  - places-menu@gnome-shell-extensions.gcampax.github.com
  - window-list@gnome-shell-extensions.gcampax.github.com
  - background-logo@fedorahosted.org
  - blur-my-shell@aunetx
  - clipboard-indicator@tudmotu.com
  - tilingshell@ferrarodomenico.com
  - rounded-window-corners@fxgn
  - weatheroclock@CleoMenezesJr.github.io
  - dynamic-music-pill@andbal
  - just-perfection-desktop@just-perfection
  - advanced-media-controller@sanjai.com
  - docker-manager@omerfarukgungor

desktop_gnome_extensions_enabled: "{{ personal_gnome_extensions_enabled }}"
