---

- name: Configure system updates
  ansible.builtin.import_tasks: system.yml

- name: Configure core packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure DNF settings
  ansible.builtin.import_tasks: dnf.yml
