---
- name: Include jetbrains tasks
  ansible.builtin.import_tasks: jetbrains.yml

- name: Include vscode tasks
  ansible.builtin.import_tasks: vscode.yml

- name: Include sdks tasks
  ansible.builtin.import_tasks: sdks.yml

- name: Include antigravity tasks
  ansible.builtin.import_tasks: antigravity.yml

- name: Include claude-code tasks
  ansible.builtin.import_tasks: claude-code.yml

- name: Include codex tasks
  ansible.builtin.import_tasks: codex.yml
