---

- name: Install Toolbox dependencies
  ansible.builtin.dnf:
    name:
      - fuse
      - libXi
      - libXrender
      - libXtst
      - fontconfig
      - gtk3
      - xcb-util-keysyms
      - glx-utils
    state: present
  become: true

- name: Check whether Toolbox is installed
  ansible.builtin.stat:
    path: "{{ desktop_target_home }}/.local/bin/jetbrains-toolbox/bin/jetbrains-toolbox"
  register: jetbrains_toolbox_binary

- name: Fetch latest JetBrains Toolbox release
  ansible.builtin.uri:
    url: "https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release"
    return_content: true
  register: jetbrains_toolbox_api
  when: not jetbrains_toolbox_binary.stat.exists and not ansible_check_mode

- name: Download JetBrains Toolbox
  ansible.builtin.get_url:
    url: "{{ jetbrains_toolbox_api.json.TBA[0].downloads.linux.link }}"
    dest: /tmp/jetbrains-toolbox.tar.gz
    mode: '0644'
  when: not jetbrains_toolbox_binary.stat.exists and not ansible_check_mode

- name: Create JetBrains Toolbox directory
  ansible.builtin.file:
    path: "{{ desktop_target_home }}/.local/bin/jetbrains-toolbox"
    state: directory
    owner: "{{ desktop_target_user }}"
    mode: "0755"
  become: true
  become_user: "{{ desktop_target_user }}"

- name: Extract JetBrains Toolbox
  ansible.builtin.unarchive:
    src: /tmp/jetbrains-toolbox.tar.gz
    dest: "{{ desktop_target_home }}/.local/bin/jetbrains-toolbox"
    remote_src: true
    creates: "{{ desktop_target_home }}/.local/bin/jetbrains-toolbox/bin/jetbrains-toolbox"
    extra_opts:
      - --strip-components=1
  become: true
  become_user: "{{ desktop_target_user }}"
  when: not jetbrains_toolbox_binary.stat.exists and not ansible_check_mode
